
workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - echo "Начинаем сборку проекта"
      - echo "Проверка текущей директории"
      - pwd
      - ls -la
      - echo "Проверка наличия Node и NPM"
      - node --version
      - npm --version
      - echo "Установка зависимостей проекта"
      - npm ci
      - echo "Инициализация Capacitor Android"
      - npx cap add android || npx cap add android --skip-appid-validation
      - echo "Сборка веб-приложения"
      - npm run build
      - echo "Синхронизация с Android"
      - npx cap sync android
      - echo "Проверка содержимого директории android"
      - ls -la android
      - echo "Подробная проверка структуры каталога android"
      - find android -name "gradlew" -type f
      - echo "Проверка структуры android/app директории"
      - ls -la android/app || echo "android/app директория не существует"
      - echo "Выполнение сборки Android"
      - cd android
      - echo "Содержимое директории android после перехода:"
      - ls -la
      - echo "Проверка текущей директории после cd android"
      - pwd
      - find . -name "gradlew" -type f
      - echo "Попытка сборки с поиском gradlew"
      - |
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew && ./gradlew clean assembleDebug
        elif [ -f "gradlew" ]; then
          chmod +x gradlew && ./gradlew clean assembleDebug
        elif [ -f "./app/gradlew" ]; then
          chmod +x ./app/gradlew && cd app && ./gradlew clean assembleDebug
        elif [ -f "app/gradlew" ]; then
          chmod +x app/gradlew && cd app && ./gradlew clean assembleDebug
        else
          echo "ОШИБКА: gradlew не найден в ожидаемых локациях"
          echo "Создаем gradlew файл с использованием gradle wrapper"
          gradle wrapper
          if [ -f "gradlew" ]; then
            chmod +x gradlew && ./gradlew clean assembleDebug
          else
            echo "Не удалось создать gradlew. Сборка невозможна."
            exit 1
          fi
        fi
    artifacts:
      - android/app/build/outputs/**/*.apk
