
workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - echo "Starting build process"
      - echo "Checking current directory"
      - pwd
      - ls -la
      - echo "Verifying Node and NPM"
      - node --version
      - npm --version
      - echo "Installing project dependencies"
      - npm ci
      - echo "Building web application"
      - npm run build
      - echo "Adding Android platform if not present"
      - npx cap add android || echo "Android platform already exists"
      - echo "Syncing with Android"
      - npx cap sync android
      - echo "Checking Android directory structure"
      - ls -la android
      - echo "Moving to Android directory"
      - cd android
      - echo "Checking for Gradle wrapper"
      - ls -la
      - |
        if [ ! -f "./gradlew" ]; then
          echo "Gradle wrapper not found, creating it"
          gradle wrapper
        fi
      - echo "Making gradlew executable"
      - chmod +x ./gradlew
      - echo "Running Gradle build"
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
