
workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - echo "Starting build process"
      - echo "Checking current directory"
      - pwd
      - ls -la
      - echo "Verifying Node and NPM"
      - node --version
      - npm --version
      - echo "Installing project dependencies"
      - npm ci
      - echo "Building web application"
      - npm run build
      - echo "Adding Android platform if not present"
      - |
        if [ ! -d "android" ]; then
          echo "Android platform not found, creating it"
          npx cap add android
        fi
      - echo "Syncing web build with Android platform"
      - npx cap sync android
      - echo "Moving to Android directory"
      - cd android
      - echo "Checking Android directory structure"
      - ls -la
      - echo "Checking for Gradle wrapper"
      - |
        if [ ! -f "./gradlew" ]; then
          echo "Gradle wrapper not found in Android project"
          echo "Running Capacitor sync again to ensure proper initialization"
          cd ..
          npx cap sync android --force
          cd android
          
          if [ ! -f "./gradlew" ]; then
            echo "Still no Gradle wrapper, attempting to initialize Gradle project"
            # First check if we have a settings.gradle file
            if [ ! -f "./settings.gradle" ] && [ ! -f "./settings.gradle.kts" ]; then
              echo "No settings.gradle found, this is unexpected"
              echo "Running gradle init to create a basic Gradle build"
              gradle init --type basic --dsl groovy
            fi
            
            echo "Now creating Gradle wrapper"
            gradle wrapper
            
            if [ ! -f "./gradlew" ]; then
              echo "Failed to create Gradle wrapper, build cannot continue"
              exit 1
            fi
          fi
          
          echo "Gradle wrapper created successfully"
          chmod +x ./gradlew
        else
          echo "Gradle wrapper found, making it executable"
          chmod +x ./gradlew
        fi
      - echo "Listing available Gradle tasks"
      - ./gradlew tasks --all || echo "Failed to list tasks, continuing anyway"
      - echo "Building Android Debug APK"
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
