
workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - echo "Начинаем сборку проекта"
      - echo "Проверка текущей директории"
      - pwd
      - ls -la
      - echo "Проверка наличия Node и NPM"
      - node --version
      - npm --version
      - echo "Установка зависимостей проекта"
      - npm ci
      - echo "Инициализация Capacitor Android"
      - npx cap add android || true
      - echo "Сборка веб-приложения"
      - npm run build
      - echo "Синхронизация с Android"
      - npx cap sync android
      - echo "Проверка содержимого директории android"
      - ls -la android
      - echo "Проверка наличия gradlew"
      - ls -la android/gradlew || echo "gradlew не найден"
      - echo "Выполнение сборки Android"
      - cd android
      - ls -la
      - if [ -f "./gradlew" ]; then chmod +x ./gradlew; else echo "ОШИБКА: gradlew не найден"; exit 1; fi
      - ./gradlew clean assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk

