workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - echo "Starting build process"
      - echo "Checking current directory"
      - pwd
      - ls -la
      - echo "Verifying Node and NPM"
      - node --version
      - npm --version
      - echo "Installing project dependencies"
      - npm ci
      - echo "Building web application"
      - npm run build
      - echo "Adding Android platform if not present"
      - |
        if [ ! -d "android" ]; then
          echo "Android platform not found, creating it"
          npx cap add android
          npx cap sync android
        fi
      - echo "Moving to Android directory"
      - cd android
      - echo "Initializing Gradle if needed"
      - |
        if [ ! -f "settings.gradle" ]; then
          echo "Initializing Gradle project"
          gradle init --type basic
        fi
      - echo "Creating Gradle wrapper if needed"
      - |
        if [ ! -f "./gradlew" ]; then
          echo "Creating Gradle wrapper"
          gradle wrapper
        fi
      - echo "Making gradlew executable"
      - chmod +x ./gradlew
      - echo "Running Gradle build"
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
