workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - echo "Начинаем сборку проекта"
      - ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
