
workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - echo "Starting build process"
      - echo "Checking current directory"
      - pwd
      - ls -la
      - echo "Verifying Node and NPM"
      - node --version
      - npm --version
      - echo "Installing project dependencies"
      - npm ci
      - echo "Building web application"
      - npm run build
      - echo "Adding Android platform if not present"
      - |
        if [ ! -d "android" ]; then
          echo "Android platform not found, creating it"
          npx cap add android
        fi
      - echo "Syncing web build with Android platform"
      - npx cap sync android
      - echo "Moving to Android directory"
      - cd android
      - echo "Checking Android directory structure"
      - ls -la
      - echo "Checking for Gradle wrapper"
      - |
        if [ ! -f "./gradlew" ]; then
          echo "Unable to find Gradle wrapper in Android project"
          echo "This is unexpected as Capacitor should generate it"
          echo "Attempting to generate it manually"
          ./gradlew wrapper
        else
          echo "Gradle wrapper found, making it executable"
          chmod +x ./gradlew
        fi
      - echo "Running Gradle tasks"
      - cd app
      - echo "Checking app directory structure"
      - ls -la
      - cd ..
      - echo "Listing available Gradle tasks"
      - ./gradlew tasks
      - echo "Building Android Debug APK"
      - ./gradlew :app:assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
